### ISSUE TITLE
Specified key was too long

### ISSUE THREAD

**Issue by benbyford** [apeisa/ProcessRedirects#19]
****Unable to install module (ProcessRedirects): Specified key was too long; max key length is 1000 bytes

Not really sure what to do to fix this. Also the module installs a page in Setup in the page tree but doesnt assign a process to it.

**Comment by isellsoap** [comment]
Got the exact same problem when switching the DB charset to `utf8mb4`. ProcessRedirects doesn’t work with `utf8mb4` apparently. 😔

**Comment by teppokoivula** [comment]
Hey @benbyford and @isellsoap! This issue should be fixed in version 2.0.0. Please let me know if there are still issues, though.

I've just installed ProcessRedirects on a database using utf8mb4,and everything seems to work fine, except that I can't yet use emojis in redirects (looks like an URL encoding issue, will take a closer look later).

Note that this is a new major version, so extra caution is recommended when updating. This version also requires ProcessWire 3.0.112+ and PHP 7.1+.
